### ISSUE TITLE
sh_callout : unkwnon function

### ISSUE THREAD

**Issue by pavlo-svirin** [radical-cybertools/radical.nge#1]
I'm getting this out put when I run example together with NGE service:

(rpi-venv2) -bash-4.2$ python 00_nge.py
guest
session id: rp.session.dtn36.psvirin.017500.0003
request backfill resources
2017-11-30 14:14:08,175: radical.pilot.nge   : MainProcess                     : MainThread     : ERROR   : oops
Traceback (most recent call last):
  File "radical-nge-service.py", line 173, in request_backfill_resources
    max_cores, max_walltime)
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/nge.py", line 83, in request_backfill_resources
    max_cores, max_walltime)
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/nge_rp.py", line 74, in request_backfill_resources
    bf = get_backfill(partition, max_cores, max_walltime)
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/utils/misc.py", line 45, in get_backfill
    out, err, ret = ru.sh_callout('showbf --blocking %s' % part)
AttributeError: 'module' object has no attribute 'sh_callout'
close panda-nge session

Traceback (most recent call last):
  File "00_nge.py", line 29, in <module>
    max_walltime=30))
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/nge.py", line 83, in request_backfill_resources
    max_cores, max_walltime)
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/nge_rps.py", line 95, in request_backfill_resources
    (partition, max_cores, max_walltime), data=request_stub)
  File "/ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/nge_rps.py", line 57, in _query
    raise RuntimeError('query failed: %s' % result['error'])
RuntimeError: query failed: AttributeError("'module' object has no attribute 'sh_callout'",)
(rpi-venv2) -bash-4.2$ vim /ccs/home/psvirin/dev/rpi-venv2/lib/python2.7/site-packages/radical/nge/utils/misc.py

**Comment by andre-merzky** [comment]
This indicates a mismatch in the `radical.utils` version. We pushed out a new release yesterday, so you should be able to install from pypi now - but updated devel or master branches would also work.
